namespace bdDevs.Shared.Records.CRM;

public record CreateCrmApplicationRecord(
    int StudentId,
    int BranchId,
    int? ProcessingOfficerId,
    int CountryId,
    int UniversityId,
    int ProgramId,
    int IntakeId,
    string? StudentSnapshotJson,
    string? ProgramSnapshotJson,
    string? OfferSnapshotJson,
    string? ConditionSnapshotJson,
    string? MetaSnapshotJson,
    byte Status,
    byte Priority,
    DateTime? AppliedDate,
    DateTime? OfferReceivedDate,
    DateTime? EnrollmentDate,
    DateTime? WithdrawnDate,
    string? OfferDetails,
    string? WithdrawalReason,
    string? RejectionReason,
    string? PortalUsername,
    string? PortalPassword,
    bool IsDeleted,
    DateTime CreatedDate,
    int CreatedBy,
    DateTime? UpdatedDate,
    int? UpdatedBy);

public record UpdateCrmApplicationRecord(
    int ApplicationId,
    int StudentId,
    int BranchId,
    int? ProcessingOfficerId,
    int CountryId,
    int UniversityId,
    int ProgramId,
    int IntakeId,
    string? StudentSnapshotJson,
    string? ProgramSnapshotJson,
    string? OfferSnapshotJson,
    string? ConditionSnapshotJson,
    string? MetaSnapshotJson,
    string? InternalRefNo,
    byte Status,
    byte Priority,
    DateTime? AppliedDate,
    DateTime? OfferReceivedDate,
    DateTime? EnrollmentDate,
    DateTime? WithdrawnDate,
    string? OfferDetails,
    string? WithdrawalReason,
    string? RejectionReason,
    string? PortalUsername,
    string? PortalPassword,
    bool IsDeleted,
    DateTime CreatedDate,
    int CreatedBy,
    DateTime? UpdatedDate,
    int? UpdatedBy);

public record DeleteCrmApplicationRecord(int ApplicationId);
public record ChangeCrmApplicationStatusRecord(int ApplicationId, byte NewStatus, int ChangedBy, string? Notes);
